name: Deploy Python to Azure

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: Production
    
    steps:
    - uses: actions/checkout@v4

    - name: Validate requirements.txt
      run: |
        if [ ! -f requirements.txt ]; then exit 1; fi
        grep -q "Flask" requirements.txt || exit 1

    - name: Set up Python 3.9
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v3
      with:
        app-name: 'kanjur'
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}

    - name: Set Startup Command
      run: |
        az webapp config set \
        --name kanjur \
        --resource-group project \
        --startup-file "gunicorn --bind=0.0.0.0 --timeout 600 --chdir /home/site/wwwroot app:app"
